
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oocl_test?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 430520
    driver-class-name: com.mysql.cj.jdbc.Driver